### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by 12thtone**

### CODE REVIEW

**Comment by 12thtone** [comment]
I added a bunch of stuff. I also ran into an issue that I haven't been able to solve. When the device runs the app, and there are no entries, the labels are not displayed. The labels display correctly after the second or third entry is added. All of the labels display correctly if the simulator is stopped and restarted or the app is killed in memory on a physical device. 

I have tried [self.tableView reloadData]; in a bunch of places, but I thought it should only need to be in notification method I call when the entry is saved in AddNoteVC, and it is dismissed. 

Everything displays correctly in the search - even if it does not in the tableView.

Thanks, 

Matt

**Comment by steveschauer** [comment]
I like the styling a lot!  I’m going out to a Bloc dinner in a bit, but hopefully I will get a chance to look at the table view issue later tonight or tomorrow morning before we meet.

We can pair on it and figure it out.

**Comment by steveschauer** [comment]
Easy!  We don’t want to reloadData, we want to performFetch.
- (void)reloadTableView:(NSNotification*)notification {
  {
      if ([[notification name] isEqualToString:@"reloadTable"])
      {
          NSLog(@"Reloading");
          NSError *error;
          if (![[self fetchedResultsController]performFetch:&error]) {
              NSLog(@"Error! %@", error);
              abort();
          }
      }
  }
  }

**Comment by 12thtone** [comment]
Awesome - thanks a lot for the help. I'll check that out in the morning.

Thanks,     Matt

On Jan 29, 2015, at 10:14 PM, steveschauer <notifications@github.com<mailto:notifications@github.com>> wrote:

Easy! We don't want to reloadData, we want to performFetch.
- (void)reloadTableView:(NSNotification*)notification {
  {
  if ([[notification name] isEqualToString:@"reloadTable"])
  {
  NSLog(@"Reloading");
  NSError *error;
  if (![[self fetchedResultsController]performFetch:&error]) {
  NSLog(@"Error! %@", error);
  abort();
  }
  }
  }
  }

> On Jan 29, 2015, at 6:32 PM, 12thtone <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> I added a bunch of stuff. I also ran into an issue that I haven't been able to solve. When the device runs the app, and there are no entries, the labels are not displayed. The labels display correctly after the second or third entry is added. All of the labels display correctly if the simulator is stopped and restarted or the app is killed in memory on a physical device.
> 
> I have tried [self.tableView reloadData]; in a bunch of places, but I thought it should only need to be in notification method I call when the entry is saved in AddNoteVC, and it is dismissed.
> 
> Everything displays correctly in the search - even if it does not in the tableView.
> 
> Thanks,
> 
> Matt
> 
> ## 
> 
> Reply to this email directly or view it on GitHub https://github.com/12thtone/NoteApp/pull/4#issuecomment-72144306.

##

**Pull request merged**
