### PR TITLE
Initial storyboarding

### PR DESCRIPTION
**Pull request by 12thtone**
I went with the Note Pad app instead of the Grade Book for this assignment - more diversity. Notes and titles can be created, deleted, and edited. It has a title, and emails, URLs, and stuff are tappable. I have messed around with getting the keyboard to behave in the addVC and editVC, using a UIScrollView, but I haven't gotten it to work. Auto layout is making it difficult. I tried the search a little also, but some of what I was finding is deprecated. I'm going to work on that next.

Hopefully this pull request makes its way to you! It's still a bit confusing.

### CODE REVIEW

**Comment by steveschauer** [comment]
That's a great start!  Here are some comments/suggestions:

* CoreDataViewController

    I don't think I like this design.  The Core Data functionality is not related to the UIViewController class.  I would recommend setting up a DataSource class that's a subclass of NSObject, and then calling those methods as needed.  If it's a singleton like we did in Blocstagram it's not coupled to the ViewController class.

* Storyboard

    You don't need to segue to a navigationController on each transition.  The framework will handle that plumbing for you.

```
    //UINavigationController *navigationController = segue.destinationViewController; 
    AddNoteViewController *addNoteViewController = (AddNoteViewController*) segue.destinationViewController;
```
screen shot 2015-01-12 at 1 39 36 pm

* [self viewDidLoad] call in viewDidAppear - do we need this?  Seems to work well without it.

**Comment by 12thtone** [comment]
Thanks for taking a look at the project.

I’ll get the CoreDataVC and the segue situations fixed.

For the [self viewDidLoad] call in viewWillAppear, I am using it as a way to reload ReadNoteVC. With it in there, the note will be updated after the user edits it. Without it, it won’t appear as updated when the EditNoteVC is dismissed.

Thanks again,      Matt


On Jan 12, 2015, at 4:43 PM, steveschauer <notifications@github.com<mailto:notifications@github.com>> wrote:


That's a great start! Here are some comments/suggestions:

  *   CoreDataViewController

I don't think I like this design. The Core Data functionality is not related to the UIViewController class. I would recommend setting up a DataSource class that's a subclass of NSObject, and then calling those methods as needed. If it's a singleton like we did in Blocstagram it's not coupled to the ViewController class.

  *   Storyboard

You don't need to segue to a navigationController on each transition. The framework will handle that plumbing for you.

    //UINavigationController *navigationController = segue.destinationViewController;
    AddNoteViewController *addNoteViewController = (AddNoteViewController*) segue.destinationViewController;


[screen shot 2015-01-12 at 1 39 36 pm]<https://cloud.githubusercontent.com/assets/4494179/5711586/95941d8c-9a60-11e4-848c-35256a35b55b.png>

  *   [self viewDidLoad] call in viewDidAppear - do we need this? Seems to work well without it.

**Comment by 12thtone** [comment]
I added a DataSource. 

I didn't change the [self viewDidLoad] call in viewDidAppear because it reloads the edited note.

Also, if I don't segue to a navigation controller, won't I lose the navigation bar? I was using it mostly for a consistent look. Please let me know if I am missing the point.

I have only messed around with some stuff for the search. It does not work at all, but I'll get some more time on it soon.

**Comment by steveschauer** [comment]
Each subsequent viewController pushed inherits the same navigation controller so that's not a problem.

**Comment by 12thtone** [comment]
This is helpful advice. I have the NotesTableVC, ReadVC, and EditVC working from NotesTableVC's navigation controller; they are show (push) segues. The AddNoteVC is modal, and it seems to want its own navigation controller to get the bar. 

Also, the EditVC pops to the original NotesTableVC, which I like better than what I had. I got rid of the [self viewDidLoad] call in viewDidAppear in ReadNoteVC.

Thanks for your help.

**Pull request merged**
